# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yo Soy Freeman
email: yosoyfreeman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  YoSoyFreeman's development blog. This site contains articles, resources and tutorials about game design, programming, 3D modelling and related topics using open source tools such as Godot engine, Blender, Material maker, Krita and other open source apps using Linux.
twitter_username: yosoyfreeman
github_username: yosoyfreeman
minimal_mistakes_skin: dark
search: true
#Seo 
google_site_verification: "wFUTmuuKIz1WDAxOy0sCQA0AcH5NnaCH0q6TvyArUnk"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Madrid

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name        : "Yo Soy Freeman"
  avatar      : "/assets/images/profile.png"
  bio         : "I'm a neurodivergent game developer and multidisciplinary artist in love with open source technology."
  links:
    - label: "Spain"
      icon: "fas fa-map-marker-alt fa-sm"
      url: "##"
    - label: "Mastodon"
      icon: "fas fa-hashtag fa-sm"
      url: "https://mastodon.gamedev.place/@YoSoyFreeman"
    - label: "GitHub"
      icon: "fas fa-code fa-sm"
      url: "https://github.com/yosoyfreeman"
    - label: "Codeberg"
      icon: "fas fa-code fa-sm"
      url: "https://codeberg.org/YoSoyFreeman"
    #- label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"

footer:
  links:
    - label: "Mastodon"
      icon: "fas fa-hashtag fa-sm"
      url: "https://mastodon.gamedev.place/@YoSoyFreeman"
    - label: "GitHub"
      icon: "fas fa-code fa-sm"
      url: "https://github.com/yosoyfreeman"
    - label: "Codeberg"
      icon: "fas fa-code fa-sm"
      url: "https://codeberg.org/YoSoyFreeman"
    #- label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/yosoyfreeman"

collections:
  assets:
    output: false
    permalink: /:collection/:path/
  materials:
    output: true
    permalink: /:collection/:path/


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      share: false
      show_date: true
      #excerpt: ""
      header:
        overlay_image: /assets/images/home/oddworld_header.jpg
        caption: "Photo credit: [**Oddworld inhabitants**](http://www.oddworld.com/)"
        
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      #classes: wide
      author_profile: true
  # _assets
  - scope:
      path: ""
      type: assets
    values:
      layout: single
      #classes: wide
      author_profile: false
   # _materials
  - scope:
      path: ""
      type: materials
    values:
      layout: single
      #classes: wide
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
